workflows:
  - name: report
    step_customizations:
      - action: REPLACE
        job: report
        step_id: upload-to-sonar
        content:
          # Currently, there is no code present in the developer documentation, so
          # we do not need it evaluated by Sonar.
          - name: Upload to Sonar
            if: false
            id: upload-to-sonar
            env:
              SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
            run: poetry run -- nox -s sonar:check
  - name: checks
    # This is needed because this project does not need `matrix-all.yml` or `matrix-exasol.yml`.
    # This job will be re-activated in:
    #   https://github.com/exasol/developer-documentation/issues/57
    remove_jobs:
      - check-workflows
